export interface SystemPreset {
  id: string;
  name: string;
  icon: string;
  accentColor: string;
  category: string;
}
export const systemPresets: SystemPreset[] = [
  {
    id: "power-platform",
    name: "Power Platform",
    icon: "layers",
    accentColor: "#6e55bf",
    category: "Microsoft",
  },
  {
    id: "power-automate",
    name: "Power Automate",
    icon: "workflow",
    accentColor: "#4775d8",
    category: "Microsoft",
  },
  {
    id: "power-apps",
    name: "Power Apps",
    icon: "app-window",
    accentColor: "#9a508e",
    category: "Microsoft",
  },
  {
    id: "dataverse",
    name: "Dataverse",
    icon: "database",
    accentColor: "#368777",
    category: "Microsoft",
  },
  {
    id: "teams",
    name: "Microsoft Teams",
    icon: "users",
    accentColor: "#6867b4",
    category: "Microsoft",
  },
  {
    id: "outlook",
    name: "Outlook",
    icon: "mail",
    accentColor: "#307dce",
    category: "Microsoft",
  },
  {
    id: "sharepoint",
    name: "SharePoint",
    icon: "files",
    accentColor: "#2d938e",
    category: "Microsoft",
  },
  {
    id: "azure",
    name: "Microsoft Azure",
    icon: "cloud",
    accentColor: "#368acc",
    category: "Microsoft",
  },
  {
    id: "appian",
    name: "Appian",
    icon: "app-window",
    accentColor: "#3560a0",
    category: "Automation",
  },
  {
    id: "uipath",
    name: "UiPath",
    icon: "bot",
    accentColor: "#dc6244",
    category: "Automation",
  },
  {
    id: "sap",
    name: "SAP",
    icon: "briefcase",
    accentColor: "#318abe",
    category: "Enterprise",
  },
  {
    id: "salesforce",
    name: "Salesforce",
    icon: "cloud",
    accentColor: "#3698c7",
    category: "Enterprise",
  },
  {
    id: "servicenow",
    name: "ServiceNow",
    icon: "circle-check",
    accentColor: "#4c916d",
    category: "Enterprise",
  },
  {
    id: "slack",
    name: "Slack",
    icon: "hash",
    accentColor: "#94508b",
    category: "Collaboration",
  },
  {
    id: "jira",
    name: "Jira",
    icon: "square-kanban",
    accentColor: "#477acc",
    category: "Collaboration",
  },
  {
    id: "aws",
    name: "AWS",
    icon: "cloud",
    accentColor: "#ca8a32",
    category: "Cloud",
  },
  {
    id: "openai",
    name: "OpenAI",
    icon: "sparkles",
    accentColor: "#558779",
    category: "AI",
  },
  {
    id: "anthropic",
    name: "Anthropic",
    icon: "sparkles",
    accentColor: "#c18365",
    category: "AI",
  },
  {
    id: "postgresql",
    name: "PostgreSQL",
    icon: "database",
    accentColor: "#507faa",
    category: "Data",
  },
  {
    id: "sql",
    name: "SQL Database",
    icon: "database",
    accentColor: "#398f99",
    category: "Data",
  },
  {
    id: "rest-api",
    name: "REST API",
    icon: "globe",
    accentColor: "#6385df",
    category: "Integration",
  },
  {
    id: "generic-database",
    name: "Generic Database",
    icon: "database",
    accentColor: "#399b94",
    category: "Data",
  },
  {
    id: "generic-application",
    name: "Generic Application",
    icon: "app-window",
    accentColor: "#5f7ec7",
    category: "General",
  },
  {
    id: "generic-cloud",
    name: "Cloud Service",
    icon: "cloud",
    accentColor: "#738bb7",
    category: "Cloud",
  },
];
