export interface SystemPreset {
  id: string;
  name: string;
  icon: string;
  accentColor: string;
  category: string;
}
export const systemPresets: SystemPreset[] = [
  {"id":"azure-functions","name":"Azure Functions","icon":"zap","category":"Microsoft Azure","accentColor":"#0078d4"},
  {"id":"azure-app-service","name":"Azure App Service","icon":"app-window","category":"Microsoft Azure","accentColor":"#0078d4"},
  {"id":"azure-sql-database","name":"Azure SQL Database","icon":"database","category":"Microsoft Azure","accentColor":"#0078d4"},
  {"id":"azure-blob-storage","name":"Azure Blob Storage","icon":"box","category":"Microsoft Azure","accentColor":"#0078d4"},
  {"id":"azure-data-lake-storage","name":"Azure Data Lake Storage","icon":"database","category":"Microsoft Azure","accentColor":"#0078d4"},
  {"id":"azure-data-factory","name":"Azure Data Factory","icon":"workflow","category":"Microsoft Azure","accentColor":"#0078d4"},
  {"id":"azure-synapse-analytics","name":"Azure Synapse Analytics","icon":"network","category":"Microsoft Azure","accentColor":"#0078d4"},
  {"id":"azure-kubernetes-service","name":"Azure Kubernetes Service","icon":"layers","category":"Microsoft Azure","accentColor":"#0078d4"},
  {"id":"azure-virtual-machines","name":"Azure Virtual Machines","icon":"server","category":"Microsoft Azure","accentColor":"#0078d4"},
  {"id":"azure-service-bus","name":"Azure Service Bus","icon":"list","category":"Microsoft Azure","accentColor":"#0078d4"},
  {"id":"azure-event-hubs","name":"Azure Event Hubs","icon":"activity","category":"Microsoft Azure","accentColor":"#0078d4"},
  {"id":"azure-key-vault","name":"Azure Key Vault","icon":"lock","category":"Microsoft Azure","accentColor":"#0078d4"},
  {"id":"microsoft-entra-id","name":"Microsoft Entra ID","icon":"shield","category":"Microsoft Azure","accentColor":"#0078d4"},
  {"id":"azure-api-management","name":"Azure API Management","icon":"globe","category":"Microsoft Azure","accentColor":"#0078d4"},
  {"id":"azure-cosmos-db","name":"Azure Cosmos DB","icon":"database","category":"Microsoft Azure","accentColor":"#0078d4"},
  {"id":"amazon-ec2","name":"Amazon EC2","icon":"server","category":"AWS","accentColor":"#c98727"},
  {"id":"amazon-s3","name":"Amazon S3","icon":"box","category":"AWS","accentColor":"#c98727"},
  {"id":"aws-lambda","name":"AWS Lambda","icon":"zap","category":"AWS","accentColor":"#c98727"},
  {"id":"amazon-rds","name":"Amazon RDS","icon":"database","category":"AWS","accentColor":"#c98727"},
  {"id":"amazon-dynamodb","name":"Amazon DynamoDB","icon":"database","category":"AWS","accentColor":"#c98727"},
  {"id":"amazon-eks","name":"Amazon EKS","icon":"layers","category":"AWS","accentColor":"#c98727"},
  {"id":"amazon-sqs","name":"Amazon SQS","icon":"list","category":"AWS","accentColor":"#c98727"},
  {"id":"amazon-api-gateway","name":"Amazon API Gateway","icon":"globe","category":"AWS","accentColor":"#c98727"},
  {"id":"google-cloud","name":"Google Cloud","icon":"cloud","category":"GCP","accentColor":"#4285f4"},
  {"id":"compute-engine","name":"Compute Engine","icon":"server","category":"GCP","accentColor":"#4285f4"},
  {"id":"cloud-storage","name":"Cloud Storage","icon":"box","category":"GCP","accentColor":"#4285f4"},
  {"id":"cloud-run","name":"Cloud Run","icon":"app-window","category":"GCP","accentColor":"#4285f4"},
  {"id":"google-kubernetes-engine","name":"Google Kubernetes Engine","icon":"layers","category":"GCP","accentColor":"#4285f4"},
  {"id":"pub-sub","name":"Pub/Sub","icon":"network","category":"GCP","accentColor":"#4285f4"},
  {"id":"bigquery","name":"BigQuery","icon":"chart-column","category":"GCP","accentColor":"#4285f4"},
  {"id":"cloud-sql","name":"Cloud SQL","icon":"database","category":"GCP","accentColor":"#4285f4"},
  {"id":"power-bi","name":"Power BI","icon":"chart-column","category":"Analytics","accentColor":"#a18230"},
  {"id":"tableau","name":"Tableau","icon":"chart-scatter","category":"Analytics","accentColor":"#a18230"},
  {"id":"alteryx","name":"Alteryx","icon":"workflow","category":"Analytics","accentColor":"#a18230"},
  {"id":"microsoft-fabric","name":"Microsoft Fabric","icon":"layers","category":"Analytics","accentColor":"#a18230"},
  {"id":"microsoft-copilot","name":"Microsoft Copilot","icon":"sparkles","category":"AI","accentColor":"#8063bf"},
  {"id":"copilot-studio","name":"Copilot Studio","icon":"bot","category":"AI","accentColor":"#8063bf"},
  {"id":"azure-openai","name":"Azure OpenAI","icon":"sparkles","category":"AI","accentColor":"#8063bf"},
  {"id":"amazon-bedrock","name":"Amazon Bedrock","icon":"bot","category":"AI","accentColor":"#8063bf"},
  {"id":"vertex-ai","name":"Vertex AI","icon":"sparkles","category":"AI","accentColor":"#8063bf"},
  {
    id: "power-platform",
    name: "Power Platform",
    icon: "layers",
    accentColor: "#6e55bf",
    category: "Microsoft",
  },
  {
    id: "power-automate",
    name: "Power Automate",
    icon: "workflow",
    accentColor: "#4775d8",
    category: "Microsoft",
  },
  {
    id: "power-apps",
    name: "Power Apps",
    icon: "app-window",
    accentColor: "#9a508e",
    category: "Microsoft",
  },
  {
    id: "dataverse",
    name: "Dataverse",
    icon: "database",
    accentColor: "#368777",
    category: "Microsoft",
  },
  {
    id: "teams",
    name: "Microsoft Teams",
    icon: "users",
    accentColor: "#6867b4",
    category: "Microsoft",
  },
  {
    id: "outlook",
    name: "Outlook",
    icon: "mail",
    accentColor: "#307dce",
    category: "Microsoft",
  },
  {
    id: "sharepoint",
    name: "SharePoint",
    icon: "files",
    accentColor: "#2d938e",
    category: "Microsoft",
  },
  {
    id: "azure",
    name: "Microsoft Azure",
    icon: "cloud",
    accentColor: "#368acc",
    category: "Microsoft",
  },
  {
    id: "appian",
    name: "Appian",
    icon: "app-window",
    accentColor: "#3560a0",
    category: "Automation",
  },
  {
    id: "uipath",
    name: "UiPath",
    icon: "bot",
    accentColor: "#dc6244",
    category: "Automation",
  },
  {
    id: "sap",
    name: "SAP",
    icon: "briefcase",
    accentColor: "#318abe",
    category: "Enterprise",
  },
  {
    id: "salesforce",
    name: "Salesforce",
    icon: "cloud",
    accentColor: "#3698c7",
    category: "Enterprise",
  },
  {
    id: "servicenow",
    name: "ServiceNow",
    icon: "circle-check",
    accentColor: "#4c916d",
    category: "Enterprise",
  },
  {
    id: "slack",
    name: "Slack",
    icon: "hash",
    accentColor: "#94508b",
    category: "Collaboration",
  },
  {
    id: "jira",
    name: "Jira",
    icon: "square-kanban",
    accentColor: "#477acc",
    category: "Collaboration",
  },
  {
    id: "aws",
    name: "AWS",
    icon: "cloud",
    accentColor: "#ca8a32",
    category: "Cloud",
  },
  {
    id: "openai",
    name: "OpenAI",
    icon: "sparkles",
    accentColor: "#558779",
    category: "AI",
  },
  {
    id: "anthropic",
    name: "Anthropic",
    icon: "sparkles",
    accentColor: "#c18365",
    category: "AI",
  },
  {
    id: "postgresql",
    name: "PostgreSQL",
    icon: "database",
    accentColor: "#507faa",
    category: "Data",
  },
  {
    id: "sql",
    name: "SQL Database",
    icon: "database",
    accentColor: "#398f99",
    category: "Data",
  },
  {
    id: "rest-api",
    name: "REST API",
    icon: "globe",
    accentColor: "#6385df",
    category: "Integration",
  },
  {
    id: "generic-database",
    name: "Generic Database",
    icon: "database",
    accentColor: "#399b94",
    category: "Data",
  },
  {
    id: "generic-application",
    name: "Generic Application",
    icon: "app-window",
    accentColor: "#5f7ec7",
    category: "General",
  },
  {
    id: "generic-cloud",
    name: "Cloud Service",
    icon: "cloud",
    accentColor: "#738bb7",
    category: "Cloud",
  },
];
