import {
  Server, Shield, Network, Monitor, Tablet,
  Activity,
  AppWindow,
  ArrowDownToLine,
  ArrowUpRight,
  Bot,
  Box,
  Braces,
  Briefcase,
  Check,
  CheckSquare,
  ChevronDown,
  ChevronRight,
  Circle,
  CircleCheck,
  Clock,
  Cloud,
  Code,
  Contact,
  Copy,
  Cpu,
  Database,
  Download,
  ExternalLink,
  File,
  Files,
  FileText,
  FolderOpen,
  GitBranch,
  Globe,
  Grid2X2,
  Group,
  Hand,
  Hash,
  HelpCircle,
  Layers,
  List,
  Lock,
  Mail,
  Maximize,
  MoreHorizontal,
  MousePointer2,
  Move,
  PanelLeftClose,
  PanelRightClose,
  Play,
  Plus,
  Redo2,
  RotateCcw,
  Save,
  Search,
  Settings,
  SlidersHorizontal,
  Sparkles,
  Split,
  Square,
  SquareKanban,
  Sun,
  Moon,
  Trash2,
  Truck,
  Undo2,
  Upload,
  User,
  UserCheck,
  Users,
  Workflow,
  X,
  Zap,
  ZoomIn,
  ZoomOut,
  Magnet,
  Unlink,
  ArrowUp,
  ArrowDown,
} from "lucide-react";
import type { LucideIcon } from "lucide-react";
export const icons: Record<string, LucideIcon> = {
  server: Server, shield: Shield, network: Network, monitor: Monitor, tablet: Tablet, lock: Lock,
  activity: Activity,
  "app-window": AppWindow,
  bot: Bot,
  box: Box,
  braces: Braces,
  briefcase: Briefcase,
  "check-square": CheckSquare,
  "circle-check": CircleCheck,
  circle: Circle,
  clock: Clock,
  cloud: Cloud,
  code: Code,
  contact: Contact,
  cpu: Cpu,
  database: Database,
  "external-link": ExternalLink,
  file: File,
  files: Files,
  "file-text": FileText,
  "git-branch": GitBranch,
  globe: Globe,
  group: Group,
  hash: Hash,
  layers: Layers,
  list: List,
  mail: Mail,
  play: Play,
  plus: Plus,
  settings: Settings,
  sparkles: Sparkles,
  split: Split,
  square: Square,
  "square-kanban": SquareKanban,
  truck: Truck,
  user: User,
  "user-check": UserCheck,
  users: Users,
  workflow: Workflow,
  zap: Zap,
};
export function Icon({
  name,
  size = 18,
  className,
}: {
  name: string;
  size?: number;
  className?: string;
}) {
  const C = icons[name] ?? Box;
  return <C size={size} strokeWidth={1.7} className={className} />;
}
export {
  ArrowDownToLine,
  ArrowUpRight,
  Check,
  ChevronDown,
  ChevronRight,
  Copy,
  Download,
  FolderOpen,
  Grid2X2,
  Hand,
  HelpCircle,
  Lock,
  Maximize,
  MoreHorizontal,
  MousePointer2,
  Move,
  PanelLeftClose,
  PanelRightClose,
  Plus,
  Redo2,
  RotateCcw,
  Save,
  Search,
  SlidersHorizontal,
  Sun,
  Moon,
  Trash2,
  Undo2,
  Upload,
  X,
  ZoomIn,
  ZoomOut,
  Magnet,
  Unlink,
  ArrowUp,
  ArrowDown,
};
